### ISSUE TITLE
Unix socket executor

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/mirakuru#121]
It would get a socket path and check if the file exists and that a server accepts connections here.

Some services (e.g. MySQL) normally listen on both an Internet TCP socket and a Unix socket: we could subclass `TCPExecutor` into one keeping both host, port and socket path.

**Comment by fizyk** [comment]
subclass `TCPExecutor` or rather create a parallel executor? probably in most cases program would just accept connections on unixsocket.

**Comment by fizyk** [comment]
I don't think basing the socket executor on tcp executor is the right thing. You'd still use unixsocket to check if the server is up and running, not the host, port. And it's not the client library. Still composition can be used to use one or the other executor if needed and have SocketOrTCPExecutor ;)
