### ISSUE TITLE
Non-HEAD HTTPExecutor Requests

### ISSUE THREAD

**Issue by href** [ClearcodeHQ/mirakuru#181]
The HTTPExecutor currently uses HEAD requests to execute the after_start_check. Unfortunately that is not always the right method. I have the case where HEAD requests are refused by a server that I need to start, whereas GET requests work.

I think it would therefore be a good idea to make the HTTP method configurable.

**Comment by fizyk** [comment]
HEAD is pretty straightforward.

With other methods there comes the issue of creating a proper response content check or proper payload. This could be settled with callbacks probably though.
