### ISSUE TITLE
OutputExecutor's banner argument does not applied to stderr

### ISSUE THREAD

**Issue by yanbe** [ClearcodeHQ/mirakuru#207]
According to SimpleExecutor's comment, it states captures stderr as well as stdout.

https://github.com/ClearcodeHQ/mirakuru/blob/2c4ea94d8b3e8dd4724c61486e44c5781604a73f/src/mirakuru/base.py#L151-L154

But its implementation does not handle stderr (only stdout)

https://github.com/ClearcodeHQ/mirakuru/blob/2c4ea94d8b3e8dd4724c61486e44c5781604a73f/src/mirakuru/base.py#L173-L181

https://github.com/ClearcodeHQ/mirakuru/blob/2c4ea94d8b3e8dd4724c61486e44c5781604a73f/src/mirakuru/base.py#L204-L208

https://github.com/ClearcodeHQ/mirakuru/blob/2c4ea94d8b3e8dd4724c61486e44c5781604a73f/src/mirakuru/base.py#L318-L321

It makes problem when use OutputExecutor, subclass of SimpleExecutor mentioned above. 
Consequently the`banner` option for constructor being ignored if a developer intended to capture it from stderr.

https://github.com/ClearcodeHQ/mirakuru/blob/2c4ea94d8b3e8dd4724c61486e44c5781604a73f/src/mirakuru/output.py#L92-L95

In my opinion, it is more consistent and useful if OutputExecutor can capture stderr too.

**Comment by fizyk** [comment]
Or have it configurable actually, whether to look for banner in stdout or stderr (at least for starters)

related: #98
