### ISSUE TITLE
Make psutil dependency optional in order to support Cygwin platform

### ISSUE THREAD

**Issue by Lucas-C** [ClearcodeHQ/mirakuru#210]
Hi.

Currently, the installation of this dependency under Cygwin gives the following output:
```
    Complete output from command python setup.py egg_info:
    platform cygwin is not supported
```

From what I found, this dependency seems optional:
- [dependency declaration in `setup.py`](https://github.com/ClearcodeHQ/mirakuru/blob/master/setup.py#L30)
- [usage in `src/mirakuru/base_env.py`](https://github.com/ClearcodeHQ/mirakuru/blob/master/src/mirakuru/base_env.py#L26)

Would it be possible to make this dependency optional please ?

**Comment by fizyk** [comment]
I so no reason not to have it optional. Ideally if it'd be skipped under Cygwin, but not necessary under other platforms
