### ISSUE TITLE
(Win23) AttributeError: module 'signal' has no attribute 'SIGKILL'

### ISSUE THREAD

**Issue by DaddyGrimmlin** [ClearcodeHQ/mirakuru#215]
Windows does not have the attribute 'SIGKILL' 

werkzeug had same problem and was fixed: 
https://github.com/pallets/werkzeug/commit/68e1ba06500914089723a3744a5ab93aa212b3a3

Can you apply a similar fix?

**Comment by DaddyGrimmlin** [comment]
Following-on issue: 

Line 180 of base.py

`preexec_fn=os.setsid`

setsid does not exist in Windows

**Comment by fizyk** [comment]
Okay, so windows needs that commented out: https://github.com/s3inlc/hashtopolis-agent/commit/2a3939999ee5924a3f8ab1768131db4171c45f8a

The shell could probably be modified to run default as True.

The biggest issue would be to actually keep those changes constant - this would require to have some windows based CI, to make sure the tests are at least running. (My dev machine is linux)

@DaddyGrimmlin please feel free to propose pull requests. You can safely suggest the the pullrequests separately for each next issue.

**Comment by fizyk** [comment]
@DaddyGrimmlin please check this pr: #218
