### ISSUE TITLE
Timeout not honoured for stop()

### ISSUE THREAD

**Issue by ulope** [ClearcodeHQ/mirakuru#252]
The documentation for the `timeout` parameter to `SimpleExecutor.__init__()` says that it's applicable to both start and stop:
https://github.com/ClearcodeHQ/mirakuru/blob/dff7019e2b39afb23deda31a729d4412234fb6cf/src/mirakuru/base.py#L86-L87

Yet `SimpleExecutor.stop()` has a hardcoded 10s timeout: https://github.com/ClearcodeHQ/mirakuru/blob/dff7019e2b39afb23deda31a729d4412234fb6cf/src/mirakuru/base.py#L291

**Comment by fizyk** [comment]
Do you have a use case where would you want to wait for the app to close by itself? Definitely don't want to wait indefinitely on close as the documentation suggest.

**Comment by ulope** [comment]
@fizyk Yes, we have a use case where a clean shutdown can take several tens of seconds. 
Would anything speak against adding a `timeout` parameter to the `stop` method?

**Comment by fizyk** [comment]
No, nothing, I just think it needs to be finite number, and not infinite as it would be now if passing None or False.

**Comment by fizyk** [comment]
#254 should cover this.

**Comment by fizyk** [comment]
@ulope please check v1.1.0
