### ISSUE TITLE
Support netcat-traditional in tests

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/mirakuru#312]
We run `nc -l 3000` in tests which works with `netcat-openbsd`, while `netcat-traditional` requires `nc -l -p 3000` (which isn't accepted by `netcat-openbsd`).

We can:

* document that `netcat-openbsd` is required for running tests, or
* autodetect which netcat implementation is installed and handle it properly, or
* change tests to run a Python socket server instead of netcat

**Comment by fizyk** [comment]
That's actually more like a feature request to support bsd, and unless there's some CI, I won't do that...
