### ISSUE TITLE
Latest release breaks up-stream packages

### ISSUE THREAD

**Issue by jwag956** [ClearcodeHQ/mirakuru#319]
We are all excited to drop python 2.0 support.

Alas - in this case - pytest-mongo (also from ClearcodeHQ) has a simple requirement.txt
that doesn't specify any mirakuru release - so this just broke pytest-mongo for python 2.7.
Not everyone is quite able/ready to drop 2.x support... I will also file an issue with pytest-mongo - since it you be a very simple fix for them..

**Comment by fizyk** [comment]
@jwag956 could you pin mirakuru version in your installation scripts or requirements? 

Unfortunately I don't have resources to do all this by Roy. Neither patience to wait. A lot of projects are dropping py2 support or already have. Like pylint. 

I'll try to release point releases with mirakuru restricted for py2 but mind that next step for all pytest plugins maintained by me will be to drop py2 support (when I get around to touch them)

**Comment by jwag956** [comment]
thanks for responding - I think you did the right thing - bumping the major release - alas upstream packages (like pytest-mongo) didn't have any dependency pinning - thus the problem.

I am still fighting with pip to see how to override a dependency within a dependency...

**Comment by fizyk** [comment]
it should be as easy as adding `mirakuru<2.0.0` next `pytest-mongo` in your requirements. In our project we actually pinned the dependencies manually to specific version, and in most cases even the depdendencies dependencies.

So even though we were using directly pytest-postgresql, we've added also a requirement for specific mirakuru version, and bumped the dependncies version only after the tests have passed.

**Comment by jwag956** [comment]
Yup - i had tried that but messed up somewhere... works fine.

**Comment by fizyk** [comment]
In the meantime I think I found the error on my part

**Comment by fizyk** [comment]
@jwag956 fixed. you can remove that requiremrnt now. the mirakuru 2.0.0 has been removed from pypi and 2.0.1 won't install on python 2.

Sorry for that

**Comment by jwag956** [comment]
thanks! simple solution that I didn't know about!
