### ISSUE TITLE
Access exit code of process after `stop`

### ISSUE THREAD

**Issue by karlb** [ClearcodeHQ/mirakuru#380]
When calling [stop](https://mirakuru.readthedocs.io/en/latest/_modules/mirakuru/base.html#SimpleExecutor.stop), the process gets removed from the executor via `_clear_process()`. Without the process object, I don't know how to check if the process exited cleanly or not. What is the recommended approach to check for clean shutdown of processes managed by mirakuru?

**Comment by fizyk** [comment]
This ought to be pretty easy to get:

https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode

**Comment by fizyk** [comment]
@karlb so far it didn't really mattered whether the exit was clean or not. Most of the processes cleaned after themselves either on the kill or start. If anything, we had the issues with hanging processes rather.

But we could transcribe the last returncode if that's needed. Won't be much work.

**Comment by karlb** [comment]
I consider a clean shutdown to be part of our testing scope, so I would clearly like to check the error code. Since mirakuru checks the exit code in other places and raises `ProcessExitedWithError` when it's not zero, doing this during `stop` would be a good approach IMO.

I can create a PR with that apporach if that helps.
