### ISSUE TITLE
ProcessFinishedWithError false positive for Java

### ISSUE THREAD

**Issue by elgohr** [ClearcodeHQ/mirakuru#388]
# The issue
Starting and stopping a Java application with TCPExecutor results in a mirakuru.exceptions.ProcessFinishedWithError (from https://github.com/ClearcodeHQ/mirakuru/blob/master/src/mirakuru/base.py#L352), as the JVM exits on exit code 143 for SIGTERM (http://journal.thobe.org/2013/02/jvms-and-kill-signals.html) instead of 9.

# How could it be fixed?
As an example the expected exit signal could be passed as an optional parameter
```
def stop(self: SimpleExecutorType, sig: int = None, exp_sig: int = 9) -> SimpleExecutorType:
```

# Current Workaround 
```
try:
   self.executor.stop()
except mirakuru.exceptions.ProcessFinishedWithError as e:
   default_jvm_sigkill_code = 143
   if e.exit_code != default_jvm_sigkill_code:
      raise e
```

**Comment by fizyk** [comment]
workaround is acceptable, unless yo uwant tot use stopped context manager.
I'll accept pull request :)

**Comment by fizyk** [comment]
@elgohr please switch to version 2.3.0
