### ISSUE TITLE
Have a finite default timeout

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/mirakuru#59]
```
class SimpleExecutor(object):
[...]
    def __init__(
            self, command, shell=False, timeout=None, sleep=0.1,
            sig_stop=signal.SIGTERM, sig_kill=signal.SIGKILL
    ):
[...]
        :param int timeout: time to wait for process to start or stop.
            if None, wait indefinitely.
[...]
```

This default makes short and obvious code hang if the after start check fails deterministically (e.g. since the started process is misconfigured, not working at all on a test machine). The solution is to pass the `timeout` argument to the executor and debug why the executor failed to start.

Unless for most uses of executors there is no reasonable maximum time needed to start the process, a finite default timeout should make such problems more obvious.

**Comment by fizyk** [comment]
I'd still leave it like it is for the same reason, requests library doesn't define any timeouts by default.
What would the finite number be? x? 2x? 3x? If you use executore, you have the chance to define exactly what you need. Same as when using requests.

I'd focus for detecting processes existed erroneously instead.

**Comment by pwilczynskiclearcode** [comment]
In both cases if default is `None` or `30` library user can change it.

Requests library doesn't need to set timeouts as almost always some servers have them (for too long http requests) so something will break your request.
In case of mirakuru, if you run a test on CI with executor. It will hang forever. Default '30 seconds' would be better. Anyone can raise it after first failure on CI. In case of no timeout, you will never see what happened. Tests hanged? CI hanged? Output hasn't been captured?

**Comment by fizyk** [comment]
yup, and I think that's the place where it should be set. 

Maybe it's not a bad thing to get the 30 seconds timeout... but I'm not convinced. I'm pretty sure we should rather improve catching the fact that the process exited one way or another, while trying to get confirmation on whether it's running or not

**Comment by mmaslowskicc** [comment]
It's not always about exiting process: the same problem occurs when using `HTTPExecutor` if the service runs but replies 500 to every request. Timeouts are the only way to detect such issues.

**Comment by fizyk** [comment]
And again, I believe it's the place where you define executor to set the desired timeout. What better place than that actually? 
Library gives the ability to use such features, not to set them for you. Especially that you don't have to hack or overwrite executors to be able to set timeouts.
