### ISSUE TITLE
Use subprocess32 (backport of Python 3.2/3.3 subprocess) rather than the stock subprocess

### ISSUE THREAD

**Issue by not-raspberry** [ClearcodeHQ/mirakuru#62]
As Python 2 documentation states:

> POSIX users (Linux, BSD, etc.) are strongly encouraged to install and use the much more recent subprocess32 module instead of the version included with python 2.7. It is a drop in replacement with better behavior in many situations.
> - https://docs.python.org/2.7/library/subprocess.html

We'll probably never support Windows (http://www.microsoft.com/en-us/windows) and I think the benefits of using the same module throughout various Python versions overweights the cost of moving Windows support from 'maybe some day' to 'na-ah'.

There is no easy way to compare `subprocess` functionality between different versions but IMO we should trust the official docs. 

https://pypi.python.org/pypi/subprocess32/ - `subprocess32`.
There is no established backport of 3.4's `subprocess`.

**Comment by fizyk** [comment]
3.4 adds only input, while subprocess32 is actually backport with 3.3's timeout parameter.

It would be neat to use it as a base (and possibly the timeout parameter), but to use it we'd have to either deprecate 3.2, or have it behave differently.

**Comment by pwilczynskiclearcode** [comment]
Maybe `subprocess32` could be used in `3.2` too :) Just to use the `timeout` parameter.

Sidenote: I just found the [EasyProcess](http://ponty.github.io/EasyProcess/usage.html#simple-example) library which looks like th `mirakuru` sibling in few ways.

**Comment by not-raspberry** [comment]
@pwilczynskiclearcode
I checked it - it can't.
