### ISSUE TITLE
[Mac m2] executor has exited with a non-zero code: -11

### ISSUE THREAD

**Issue by lhoestq** [ClearcodeHQ/mirakuru#642]
For some reason Mirakuru executor.stop() with a 3.9.15 python command on Mac with ARM chip fails because the program returns -11 exit code (-SIGSEGV) instead of -15 (-SIGTERM):

```python
        if exit_code and exit_code != expected_returncode:
>           raise ProcessFinishedWithError(self, exit_code)
E           mirakuru.exceptions.ProcessFinishedWithError: The process invoked by the <mirakuru.output.OutputExecutor: "xxx/python xxx/main.py" 0x14c071520> executor has exited with a non-zero code: -11.
```

I don't have a ton of bandwidth right now to investigate in depth, but I wanted to share this behavior in case someone knows more about it.

On a linux machine it succeeds because it returns exit code -15 as expected.

I just workaround this by specifying `expected_returncode`

**Comment by fizyk** [comment]
I will not be able to investigate since I do not own any mac machine let alone m2 based one. But if anyone could investigate and find reason behind the different exit code, would be great :)

**Comment by fizyk** [comment]
https://stackoverflow.com/questions/1564372/what-causes-a-sigsegv but @lhoestq wouldn't that be some issue with the program you're running i=underneath that's not working correctly on m2 chipsets? Have you tried to check it directly?

**Comment by lhoestq** [comment]
Yea I think so, I just observed a segfault by running it outside of mirakuru. thanks
