### ISSUE TITLE
Passing the command as a list collides with shell=True

### ISSUE THREAD

**Issue by not-raspberry** [ClearcodeHQ/mirakuru#69]
What happens:

```
In [1]: from mirakuru import SimpleExecutor

In [2]: e = SimpleExecutor(['echo' , '"'], shell=True)

In [3]: e.start()

In [4]: /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file


In [4]: e.process.poll()
Out[4]: 1

In [5]: e.command
Out[5]: 'echo "'
```

What should probably happen:
The command should get shell-escaped and should be: `'echo \'"\''`

Shell-escaping is a cumbersome in Python stdlib because before 2.7 there was an undocumented function `quote` in `pipes`, in 2.7 it became documented and deprecated, in 3.0 it disappeared to reappear in 3.3 in `shlex` where it belongs.

We may use: https://pypi.python.org/pypi/shellescape or require commands to be passed as strings (unicodes) if `shell` is `True`.

By the way `subprocess.Popen` behaves weirdly when `shell=True` is used with a command as a list. What happens is the command-list gets glued to `['/bin/sh', '-c']`:

`args = ["/bin/sh", "-c"] + args`

And `/bin/sh` ignores everything but the first arg, like:

```
 sh -c 'echo aaa' asd asd a sdasd asa 
aaa
```

So If it makes no sense to pass lists with `shell=True`, let's maybe prohibit that.

**Comment by fizyk** [comment]
actually it doesn't collide with shell=True

``` python
executor = SimpleExecutor(command='echo "', shell=True)
```

This will result in `ValueError: No closing quotation` so you'd have to escape it anyway.

See this lines: https://github.com/ClearcodeHQ/mirakuru/blob/master/mirakuru/base.py#L109

It was introducedto provide consistency, but to be fully consisten, maybe we should join list and split it back using shlex anyway? Then we'd get consistent errors at least.

**Comment by mmaslowskicc** [comment]
Now shlex is easily available, since we stopped supporting Python 2.

List with `shell=True` can be useful if running portable scripts (are such using mirakuru?) on Windows.

I think applying shlex.quote before joining, just in this case, should be less risky.
