### ISSUE TITLE
Incorporate good patterns from easyprocess into mirakuru

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [ClearcodeHQ/mirakuru#88]
http://easyprocess.readthedocs.org/en/latest/#usage
EasyProcess library has a nice style of calling subsequent methods:

```
.start().sleep(1).stop().stdout
```

To mimic this approach mirakuru would need to return `self` in most of Executor methods.

**Comment by fizyk** [comment]
okay, method chaining landed within mirakuru
